name: Compilador de Kernel Samsung A20s

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Instalar Herramientas de Compilacion
      run: |
        sudo apt-get update -y
        sudo apt-get install -y bc bison build-essential flex libelf-dev libssl-dev tcl-dev zip wget unzip

    - name: Descargar y Descomprimir Codigo Fuente del Kernel
      run: |
        wget https://github.com -O kernel.zip
        unzip kernel.zip
        mv android_kernel_samsung_a20s-eleven kernel-source
        
    - name: Descargar Compilador (Clang/GCC)
      run: |
        wget https://github.com -O toolchain.zip
        unzip toolchain.zip
        mv gcc-arm64-gcc-master toolchain

    - name: Compilar Kernel
      run: |
        cd kernel-source
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=../toolchain/bin/aarch64-elf-
        make O=out a20s_defconfig
        make O=out -j$(nproc --all)

    - name: Subir Archivo Terminado
      uses: actions/upload-artifact@v4
      with:
        name: Kernel_A20s_Android12
        path: kernel-source/out/arch/arm64/boot/Image.gz
