name: Compilador de Kernel Samsung A20s

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Instalar Herramientas de Compilacion
      run: |
        sudo apt-get update -y
        sudo apt-get install -y bc bison build-essential flex libelf-dev libssl-dev tcl-dev zip wget unzip

    - name: Descargar y Descomprimir Codigo Fuente del Kernel
      run: |
        wget https://github.com -O kernel.zip
        unzip kernel.zip
        mv android_kernel_samsung_a20s-eleven kernel-source
        
    - name: Descargar Compilador GCC Estable y Ligero
      run: |
        wget https://linaro.org -O gcc.tar.xz
        mkdir toolchain
        tar -xf gcc.tar.xz -C toolchain --strip-components=1

    - name: Compilar Kernel
      run: |
        cd kernel-source
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=${{ github.workspace }}/toolchain/bin/aarch64-linux-gnu-
        
        # Limpieza previa profunda
        make O=out clean
        make O=out mrproper
        
        # Cargar configuracion base de Samsung
        make O=out a20s_defconfig
        
        # EL TRUCO DEFINITIVO: Compilar con UN SOLO NÚCLEO (-j1) para no saturar la RAM
        make O=out -j1

    - name: Subir Archivo Terminado
      uses: actions/upload-artifact@v4
      with:
        name: Kernel_A20s_Android12
        path: kernel-source/out/arch/arm64/boot/Image.gz
